server:
  port: 8089

logging:
  level:
    '[org.springframework.web]': DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bike_report
    username: root
    password: jkHAnYXFU1
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true